### ISSUE TITLE
PROBLEM SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by sparta3355** [cclabsInc/RFCrack#13]
root@kali:~/RFCrack# python RFCrack.py -j -F 433000000
Traceback (most recent call last):
  File "RFCrack.py", line 7, in <module>
    import src.attacks as attacks
  File "/root/RFCrack/src/attacks.py", line 3, in <module>
    import findDevices, jam, utilities
  File "/root/RFCrack/src/utilities.py", line 4, in <module>
    import Clicker
  File "/root/RFCrack/src/Clicker.py", line 1, in <module>
    import matplotlib.pyplot as plt
  File "/usr/local/lib/python2.7/dist-packages/matplotlib/__init__.py", line 126, in <module>
    from . import cbook
  File "/usr/local/lib/python2.7/dist-packages/matplotlib/cbook/__init__.py", line 34, in <module>
    import numpy as np
  File "/usr/lib/python2.7/dist-packages/numpy/__init__.py", line 142, in <module>
    from . import core
  File "/usr/lib/python2.7/dist-packages/numpy/core/__init__.py", line 95, in <module>
    from . import numeric
  File "/usr/lib/python2.7/dist-packages/numpy/core/numeric.py", line 3095, in <module>
    from . import arrayprint
  File "/usr/lib/python2.7/dist-packages/numpy/core/arrayprint.py", line 90
    if threshold is not sys.maxsize
                                  ^
SyntaxError: invalid syntax

**Comment by cclabsInc** [comment]
Those syntax errors appear to be coming from your 3rd party libraries...

**Comment by pompel123** [comment]
Could it be the space in "init .py"?

**Comment by cclabsInc** [comment]
I don't think so or it would have broken it for everyone over the last 2 years, but try deleting the space and seeing if it works...  I will check it when i get a chance but I am on travel and not doing RF research at the moment...   Waiting on the python3 libraries associated with this project to re-code RFCrack to work with python3 when released.  But those are in very slow development at the moment I believe they have been working on that since 2018.
